dist: bionic
env: DB=mysql
language: java
sudo: true
jdk: oraclejdk11
services:
  - mysql
before_install:
  - chmod +x mvnw
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -proot
  - sudo service mysql restart